fixed helm chart test
redhat-cop/gitwebhook-operator pull request #2
Opened 2022-11-26 15:20 UTC by raffaelespazzoli

removed nginx controller

2022-11-28 20:53 UTC, raffaelespazzoli commented
so I made a mess, somehow I pushed to upstream instead of origin (I think because after the repo transfer origin didn't actually exist anymore), so after this merge we should also delete this branch. @sabre1041

2022-11-29 01:11 UTC, sabre1041 requested changes
Small change

2022-11-29 01:11 UTC, sabre1041 commented on config/local-development/tilt/replace-image.yaml
> +          image: quay.io/gitwebhook-operator/gitwebhook-operator:latest
```suggestion
          image: quay.io/redhat-cop/gitwebhook-operator:latest
```

2022-11-29 01:41 UTC, raffaelespazzoli commented
suggestion commited

2022-11-29 01:48 UTC, sabre1041 approved these changes
LGTM

2022-11-29 01:48 UTC, merged